name: Main branch
on:
  push:
    branches:
      - main

jobs:
  check:
    strategy:
      matrix:
        platform:
          - macos
          - ubuntu
          - windows
        features:
          - default
          - with-tokio

    name: "Check on ${{ matrix.platform }} (feat: ${{ matrix.features }})"
    runs-on: "${{ matrix.platform }}-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features ${{ matrix.features }}
