name: Try this
on:
  pull_request:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos]
        features:
          - default
          - with-tokio
        toolchain:
          - stable
          - 1.51.0
          - 1.52.0
          - 1.53.0
          - 1.54.0
          - 1.55.0
          - 1.56.0
          - 1.57.0
          - 1.58.0
          - 1.59.0
          - 1.60.0
          - 1.61.0
          - 1.62.0
          - 1.63.0
          - 1.64.0
          - 1.65.0
    name: "Test on ${{ matrix.platform }} with Rust ${{ matrix.toolchain }} (feat: ${{ matrix.features }})"
    runs-on: "${{ matrix.platform }}-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "${{ matrix.toolchain }}"
          default: true

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features ${{ matrix.features }}
